<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>AlAnvar</RootNamespace>
    <StringsNamespace>AlAnvar.Common</StringsNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>disable</Nullable>
    <TrimMode>partial</TrimMode>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <IsAotCompatible>true</IsAotCompatible>
    <CsWinRTAotWarningLevel>2</CsWinRTAotWarningLevel>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <Version>3.0.0</Version>
    <!--Remove git hash from assembly informational version in .NET >= 8, Example: false = 1.0.0, true = 1.0.0+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishAot>False</PublishAot>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <DefaultLanguage>fa-IR</DefaultLanguage>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Assets\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Assets\NavViewMenu\AppData.json" />
    <AdditionalFiles Include="@(Page)" />
    <AdditionalFiles Include="Strings\en-US\Resources.resw" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!-- 
	Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
	Tools extension to be activated for this project even if the Windows App SDK Nuget
	package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Animations" Version="8.3.260402-preview2" />
    <PackageReference Include="CommunityToolkit.WinUI.Collections" Version="8.3.260402-preview2" />
    <PackageReference Include="CommunityToolkit.Labs.WinUI.Ribbon" Version="0.1.250826-build.2212" />
    <PackageReference Include="DevWinUI" Version="10.0.0-Preview3" />
    <PackageReference Include="DevWinUI.SourceGenerator" Version="10.0.0-Preview3" />
    <PackageReference Include="Downloader" Version="5.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.0-prerelease.251115.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.1.3" />
    <PackageReference Include="nucs.JsonSettings" Version="2.0.2" />
    <PackageReference Include="nucs.JsonSettings.AutoSaveGenerator" Version="2.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="WinUI.TableView" Version="1.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AlAnvar.Database\AlAnvar.Database.csproj" />
  </ItemGroup>

  <!-- 
	Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
	Explorer "Package and Publish" context menu entry to be enabled for this project even if 
	the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <Target Name="RemoveUnwantedSatelliteAssemblies" AfterTargets="Publish">
    <ItemGroup>
      <CultureDirsToRemove Include="$(PublishDir)af;$(PublishDir)ar;$(PublishDir)az;$(PublishDir)bg;$(PublishDir)bn;$(PublishDir)bn-BD;$(PublishDir)bs;$(PublishDir)ca;$(PublishDir)cs;$(PublishDir)da;$(PublishDir)de;$(PublishDir)el;$(PublishDir)fi;$(PublishDir)fi-FI;$(PublishDir)fr;$(PublishDir)fr-BE;$(PublishDir)he;$(PublishDir)hi;$(PublishDir)hr;$(PublishDir)hu;$(PublishDir)hy;$(PublishDir)id;$(PublishDir)is;$(PublishDir)it;$(PublishDir)ja;$(PublishDir)ko;$(PublishDir)ko-KR;$(PublishDir)ku;$(PublishDir)lv;$(PublishDir)ms;$(PublishDir)ms-MY;$(PublishDir)mt;$(PublishDir)nb;$(PublishDir)nb-NO;$(PublishDir)nl;$(PublishDir)pl;$(PublishDir)pt;$(PublishDir)pt-BR;$(PublishDir)ro;$(PublishDir)ru;$(PublishDir)sk;$(PublishDir)sl;$(PublishDir)sr;$(PublishDir)sr-Latn;$(PublishDir)sv;$(PublishDir)th;$(PublishDir)th-TH;$(PublishDir)tr;$(PublishDir)uk;$(PublishDir)uz;$(PublishDir)uz-Cyrl-UZ;$(PublishDir)uz-Latn-UZ;$(PublishDir)vi;$(PublishDir)zh-CN;$(PublishDir)zh-Hans;$(PublishDir)zh-Hant" />
    </ItemGroup>
    <RemoveDir Directories="@(CultureDirsToRemove)" ContinueOnError="true" />
  </Target>
</Project>
