// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public partial class AlAnvarDBContextModel
    {
        private AlAnvarDBContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8b34a9de-3c06-43f6-a4a3-bea6580b6168"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var quranAudioTable = QuranAudioTableEntityType.Create(this);
            var quranCleanTable = QuranCleanTableEntityType.Create(this);
            var quranFavoriteTable = QuranFavoriteTableEntityType.Create(this);
            var quranMetadataTable = QuranMetadataTableEntityType.Create(this);
            var quranNoteTable = QuranNoteTableEntityType.Create(this);
            var quranTable = QuranTableEntityType.Create(this);
            var quranTafsirNameTable = QuranTafsirNameTableEntityType.Create(this);
            var quranTafsirTable = QuranTafsirTableEntityType.Create(this);
            var quranTranslationTable = QuranTranslationTableEntityType.Create(this);

            QuranAudioTableEntityType.CreateAnnotations(quranAudioTable);
            QuranCleanTableEntityType.CreateAnnotations(quranCleanTable);
            QuranFavoriteTableEntityType.CreateAnnotations(quranFavoriteTable);
            QuranMetadataTableEntityType.CreateAnnotations(quranMetadataTable);
            QuranNoteTableEntityType.CreateAnnotations(quranNoteTable);
            QuranTableEntityType.CreateAnnotations(quranTable);
            QuranTafsirNameTableEntityType.CreateAnnotations(quranTafsirNameTable);
            QuranTafsirTableEntityType.CreateAnnotations(quranTafsirTable);
            QuranTranslationTableEntityType.CreateAnnotations(quranTranslationTable);

            AddAnnotation("ProductVersion", "10.0.1");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var quranAudioTable = FindEntityType("AlAnvar.Database.Tables.QuranAudioTable")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            quranAudioTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var alAnvarDatabaseTablesQuranAudioTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranAudioTable", null, relationalModel);
            var dirNameColumnBase = new ColumnBase<ColumnMappingBase>("DirName", "TEXT", alAnvarDatabaseTablesQuranAudioTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("DirName", dirNameColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranAudioTableTableBase);
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("Id", idColumnBase);
            var isActiveColumnBase = new ColumnBase<ColumnMappingBase>("IsActive", "INTEGER", alAnvarDatabaseTablesQuranAudioTableTableBase);
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("IsActive", isActiveColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", alAnvarDatabaseTablesQuranAudioTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("Name", nameColumnBase);
            var persianNameColumnBase = new ColumnBase<ColumnMappingBase>("PersianName", "TEXT", alAnvarDatabaseTablesQuranAudioTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("PersianName", persianNameColumnBase);
            var urlColumnBase = new ColumnBase<ColumnMappingBase>("Url", "TEXT", alAnvarDatabaseTablesQuranAudioTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranAudioTableTableBase.Columns.Add("Url", urlColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranAudioTable", alAnvarDatabaseTablesQuranAudioTableTableBase);
            var alAnvarDatabaseTablesQuranAudioTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranAudioTable, alAnvarDatabaseTablesQuranAudioTableTableBase, null);
            alAnvarDatabaseTablesQuranAudioTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranAudioTableMappingBase, false);
            defaultTableMappings.Add(alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, quranAudioTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dirNameColumnBase, quranAudioTable.FindProperty("DirName")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isActiveColumnBase, quranAudioTable.FindProperty("IsActive")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, quranAudioTable.FindProperty("Name")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)persianNameColumnBase, quranAudioTable.FindProperty("PersianName")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)urlColumnBase, quranAudioTable.FindProperty("Url")!, alAnvarDatabaseTablesQuranAudioTableMappingBase);

            var tableMappings = new List<TableMapping>();
            quranAudioTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var audioTable = new Table("Audio", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", audioTable);
            audioTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var dirNameColumn = new Column("DirName", "TEXT", audioTable)
            {
                IsNullable = true
            };
            audioTable.Columns.Add("DirName", dirNameColumn);
            dirNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(dirNameColumn);
            var isActiveColumn = new Column("IsActive", "INTEGER", audioTable);
            audioTable.Columns.Add("IsActive", isActiveColumn);
            isActiveColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isActiveColumn);
            var nameColumn = new Column("Name", "TEXT", audioTable)
            {
                IsNullable = true
            };
            audioTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var persianNameColumn = new Column("PersianName", "TEXT", audioTable)
            {
                IsNullable = true
            };
            audioTable.Columns.Add("PersianName", persianNameColumn);
            persianNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(persianNameColumn);
            var urlColumn = new Column("Url", "TEXT", audioTable)
            {
                IsNullable = true
            };
            audioTable.Columns.Add("Url", urlColumn);
            urlColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(urlColumn);
            relationalModel.Tables.Add(("Audio", null), audioTable);
            var audioTableMapping = new TableMapping(quranAudioTable, audioTable, null);
            audioTable.AddTypeMapping(audioTableMapping, false);
            tableMappings.Add(audioTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, quranAudioTable.FindProperty("Id")!, audioTableMapping);
            RelationalModel.CreateColumnMapping(dirNameColumn, quranAudioTable.FindProperty("DirName")!, audioTableMapping);
            RelationalModel.CreateColumnMapping(isActiveColumn, quranAudioTable.FindProperty("IsActive")!, audioTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, quranAudioTable.FindProperty("Name")!, audioTableMapping);
            RelationalModel.CreateColumnMapping(persianNameColumn, quranAudioTable.FindProperty("PersianName")!, audioTableMapping);
            RelationalModel.CreateColumnMapping(urlColumn, quranAudioTable.FindProperty("Url")!, audioTableMapping);
            var pK_Audio = new UniqueConstraint("PK_Audio", audioTable, new[] { idColumn });
            audioTable.PrimaryKey = pK_Audio;
            pK_Audio.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Audio));
            var pK_AudioKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranAudioTable",
                new[] { "Id" });
            pK_Audio.MappedKeys.Add(pK_AudioKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AudioKey).Add(pK_Audio);
            audioTable.UniqueConstraints.Add("PK_Audio", pK_Audio);

            var quranCleanTable = FindEntityType("AlAnvar.Database.Tables.QuranCleanTable")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            quranCleanTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var alAnvarDatabaseTablesQuranCleanTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranCleanTable", null, relationalModel);
            var audioFileNameColumnBase = new ColumnBase<ColumnMappingBase>("AudioFileName", "TEXT", alAnvarDatabaseTablesQuranCleanTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("AudioFileName", audioFileNameColumnBase);
            var ayaColumnBase = new ColumnBase<ColumnMappingBase>("Aya", "TEXT", alAnvarDatabaseTablesQuranCleanTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("Aya", ayaColumnBase);
            var ayaIdColumnBase = new ColumnBase<ColumnMappingBase>("AyaId", "INTEGER", alAnvarDatabaseTablesQuranCleanTableTableBase);
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("AyaId", ayaIdColumnBase);
            var hizbIdColumnBase = new ColumnBase<ColumnMappingBase>("HizbId", "INTEGER", alAnvarDatabaseTablesQuranCleanTableTableBase);
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("HizbId", hizbIdColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranCleanTableTableBase);
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("Id", idColumnBase0);
            var juzIdColumnBase = new ColumnBase<ColumnMappingBase>("JuzId", "INTEGER", alAnvarDatabaseTablesQuranCleanTableTableBase);
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("JuzId", juzIdColumnBase);
            var suraIdColumnBase = new ColumnBase<ColumnMappingBase>("SuraId", "INTEGER", alAnvarDatabaseTablesQuranCleanTableTableBase);
            alAnvarDatabaseTablesQuranCleanTableTableBase.Columns.Add("SuraId", suraIdColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranCleanTable", alAnvarDatabaseTablesQuranCleanTableTableBase);
            var alAnvarDatabaseTablesQuranCleanTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranCleanTable, alAnvarDatabaseTablesQuranCleanTableTableBase, null);
            alAnvarDatabaseTablesQuranCleanTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranCleanTableMappingBase, false);
            defaultTableMappings0.Add(alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, quranCleanTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)audioFileNameColumnBase, quranCleanTable.FindProperty("AudioFileName")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaColumnBase, quranCleanTable.FindProperty("Aya")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaIdColumnBase, quranCleanTable.FindProperty("AyaId")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hizbIdColumnBase, quranCleanTable.FindProperty("HizbId")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)juzIdColumnBase, quranCleanTable.FindProperty("JuzId")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)suraIdColumnBase, quranCleanTable.FindProperty("SuraId")!, alAnvarDatabaseTablesQuranCleanTableMappingBase);

            var tableMappings0 = new List<TableMapping>();
            quranCleanTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var quranCleanTable0 = new Table("QuranClean", null, relationalModel);
            var idColumn0 = new Column("Id", "INTEGER", quranCleanTable0);
            quranCleanTable0.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn0);
            var audioFileNameColumn = new Column("AudioFileName", "TEXT", quranCleanTable0)
            {
                IsNullable = true
            };
            quranCleanTable0.Columns.Add("AudioFileName", audioFileNameColumn);
            audioFileNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(audioFileNameColumn);
            var ayaColumn = new Column("Aya", "TEXT", quranCleanTable0)
            {
                IsNullable = true
            };
            quranCleanTable0.Columns.Add("Aya", ayaColumn);
            ayaColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ayaColumn);
            var ayaIdColumn = new Column("AyaId", "INTEGER", quranCleanTable0);
            quranCleanTable0.Columns.Add("AyaId", ayaIdColumn);
            ayaIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(ayaIdColumn);
            var hizbIdColumn = new Column("HizbId", "INTEGER", quranCleanTable0);
            quranCleanTable0.Columns.Add("HizbId", hizbIdColumn);
            hizbIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(hizbIdColumn);
            var juzIdColumn = new Column("JuzId", "INTEGER", quranCleanTable0);
            quranCleanTable0.Columns.Add("JuzId", juzIdColumn);
            juzIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(juzIdColumn);
            var suraIdColumn = new Column("SuraId", "INTEGER", quranCleanTable0);
            quranCleanTable0.Columns.Add("SuraId", suraIdColumn);
            suraIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(suraIdColumn);
            relationalModel.Tables.Add(("QuranClean", null), quranCleanTable0);
            var quranCleanTableMapping = new TableMapping(quranCleanTable, quranCleanTable0, null);
            quranCleanTable0.AddTypeMapping(quranCleanTableMapping, false);
            tableMappings0.Add(quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, quranCleanTable.FindProperty("Id")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(audioFileNameColumn, quranCleanTable.FindProperty("AudioFileName")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(ayaColumn, quranCleanTable.FindProperty("Aya")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(ayaIdColumn, quranCleanTable.FindProperty("AyaId")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(hizbIdColumn, quranCleanTable.FindProperty("HizbId")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(juzIdColumn, quranCleanTable.FindProperty("JuzId")!, quranCleanTableMapping);
            RelationalModel.CreateColumnMapping(suraIdColumn, quranCleanTable.FindProperty("SuraId")!, quranCleanTableMapping);
            var pK_QuranClean = new UniqueConstraint("PK_QuranClean", quranCleanTable0, new[] { idColumn0 });
            quranCleanTable0.PrimaryKey = pK_QuranClean;
            pK_QuranClean.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_QuranClean));
            var pK_QuranCleanKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranCleanTable",
                new[] { "Id" });
            pK_QuranClean.MappedKeys.Add(pK_QuranCleanKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_QuranCleanKey).Add(pK_QuranClean);
            quranCleanTable0.UniqueConstraints.Add("PK_QuranClean", pK_QuranClean);

            var quranFavoriteTable = FindEntityType("AlAnvar.Database.Tables.QuranFavoriteTable")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            quranFavoriteTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var alAnvarDatabaseTablesQuranFavoriteTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranFavoriteTable", null, relationalModel);
            var ayaIdColumnBase0 = new ColumnBase<ColumnMappingBase>("AyaId", "INTEGER", alAnvarDatabaseTablesQuranFavoriteTableTableBase);
            alAnvarDatabaseTablesQuranFavoriteTableTableBase.Columns.Add("AyaId", ayaIdColumnBase0);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranFavoriteTableTableBase);
            alAnvarDatabaseTablesQuranFavoriteTableTableBase.Columns.Add("Id", idColumnBase1);
            var suraIdColumnBase0 = new ColumnBase<ColumnMappingBase>("SuraId", "INTEGER", alAnvarDatabaseTablesQuranFavoriteTableTableBase);
            alAnvarDatabaseTablesQuranFavoriteTableTableBase.Columns.Add("SuraId", suraIdColumnBase0);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranFavoriteTable", alAnvarDatabaseTablesQuranFavoriteTableTableBase);
            var alAnvarDatabaseTablesQuranFavoriteTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranFavoriteTable, alAnvarDatabaseTablesQuranFavoriteTableTableBase, null);
            alAnvarDatabaseTablesQuranFavoriteTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranFavoriteTableMappingBase, false);
            defaultTableMappings1.Add(alAnvarDatabaseTablesQuranFavoriteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, quranFavoriteTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranFavoriteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaIdColumnBase0, quranFavoriteTable.FindProperty("AyaId")!, alAnvarDatabaseTablesQuranFavoriteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)suraIdColumnBase0, quranFavoriteTable.FindProperty("SuraId")!, alAnvarDatabaseTablesQuranFavoriteTableMappingBase);

            var tableMappings1 = new List<TableMapping>();
            quranFavoriteTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var favoritesTable = new Table("Favorites", null, relationalModel);
            var idColumn1 = new Column("Id", "INTEGER", favoritesTable);
            favoritesTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn1);
            var ayaIdColumn0 = new Column("AyaId", "INTEGER", favoritesTable);
            favoritesTable.Columns.Add("AyaId", ayaIdColumn0);
            ayaIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(ayaIdColumn0);
            var suraIdColumn0 = new Column("SuraId", "INTEGER", favoritesTable);
            favoritesTable.Columns.Add("SuraId", suraIdColumn0);
            suraIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(suraIdColumn0);
            relationalModel.Tables.Add(("Favorites", null), favoritesTable);
            var favoritesTableMapping = new TableMapping(quranFavoriteTable, favoritesTable, null);
            favoritesTable.AddTypeMapping(favoritesTableMapping, false);
            tableMappings1.Add(favoritesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, quranFavoriteTable.FindProperty("Id")!, favoritesTableMapping);
            RelationalModel.CreateColumnMapping(ayaIdColumn0, quranFavoriteTable.FindProperty("AyaId")!, favoritesTableMapping);
            RelationalModel.CreateColumnMapping(suraIdColumn0, quranFavoriteTable.FindProperty("SuraId")!, favoritesTableMapping);
            var pK_Favorites = new UniqueConstraint("PK_Favorites", favoritesTable, new[] { idColumn1 });
            favoritesTable.PrimaryKey = pK_Favorites;
            pK_Favorites.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Favorites));
            var pK_FavoritesKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranFavoriteTable",
                new[] { "Id" });
            pK_Favorites.MappedKeys.Add(pK_FavoritesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FavoritesKey).Add(pK_Favorites);
            favoritesTable.UniqueConstraints.Add("PK_Favorites", pK_Favorites);

            var quranMetadataTable = FindEntityType("AlAnvar.Database.Tables.QuranMetadataTable")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            quranMetadataTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var alAnvarDatabaseTablesQuranMetadataTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranMetadataTable", null, relationalModel);
            var ayaColumnBase0 = new ColumnBase<ColumnMappingBase>("Aya", "INTEGER", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Aya", ayaColumnBase0);
            var englishNameColumnBase = new ColumnBase<ColumnMappingBase>("EnglishName", "TEXT", alAnvarDatabaseTablesQuranMetadataTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("EnglishName", englishNameColumnBase);
            var finglishNameColumnBase = new ColumnBase<ColumnMappingBase>("FinglishName", "TEXT", alAnvarDatabaseTablesQuranMetadataTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("FinglishName", finglishNameColumnBase);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Id", idColumnBase2);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", alAnvarDatabaseTablesQuranMetadataTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Name", nameColumnBase0);
            var orderColumnBase = new ColumnBase<ColumnMappingBase>("Order", "INTEGER", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Order", orderColumnBase);
            var rukusColumnBase = new ColumnBase<ColumnMappingBase>("Rukus", "INTEGER", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Rukus", rukusColumnBase);
            var startColumnBase = new ColumnBase<ColumnMappingBase>("Start", "INTEGER", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Start", startColumnBase);
            var typeColumnBase = new ColumnBase<ColumnMappingBase>("Type", "TEXT", alAnvarDatabaseTablesQuranMetadataTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranMetadataTableTableBase.Columns.Add("Type", typeColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranMetadataTable", alAnvarDatabaseTablesQuranMetadataTableTableBase);
            var alAnvarDatabaseTablesQuranMetadataTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranMetadataTable, alAnvarDatabaseTablesQuranMetadataTableTableBase, null);
            alAnvarDatabaseTablesQuranMetadataTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranMetadataTableMappingBase, false);
            defaultTableMappings2.Add(alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, quranMetadataTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaColumnBase0, quranMetadataTable.FindProperty("Aya")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)englishNameColumnBase, quranMetadataTable.FindProperty("EnglishName")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)finglishNameColumnBase, quranMetadataTable.FindProperty("FinglishName")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, quranMetadataTable.FindProperty("Name")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)orderColumnBase, quranMetadataTable.FindProperty("Order")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)rukusColumnBase, quranMetadataTable.FindProperty("Rukus")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)startColumnBase, quranMetadataTable.FindProperty("Start")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)typeColumnBase, quranMetadataTable.FindProperty("Type")!, alAnvarDatabaseTablesQuranMetadataTableMappingBase);

            var tableMappings2 = new List<TableMapping>();
            quranMetadataTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var chapterPropertyTable = new Table("ChapterProperty", null, relationalModel);
            var idColumn2 = new Column("Id", "INTEGER", chapterPropertyTable);
            chapterPropertyTable.Columns.Add("Id", idColumn2);
            idColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn2);
            var ayaColumn0 = new Column("Aya", "INTEGER", chapterPropertyTable);
            chapterPropertyTable.Columns.Add("Aya", ayaColumn0);
            ayaColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(ayaColumn0);
            var englishNameColumn = new Column("EnglishName", "TEXT", chapterPropertyTable)
            {
                IsNullable = true
            };
            chapterPropertyTable.Columns.Add("EnglishName", englishNameColumn);
            englishNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(englishNameColumn);
            var finglishNameColumn = new Column("FinglishName", "TEXT", chapterPropertyTable)
            {
                IsNullable = true
            };
            chapterPropertyTable.Columns.Add("FinglishName", finglishNameColumn);
            finglishNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(finglishNameColumn);
            var nameColumn0 = new Column("Name", "TEXT", chapterPropertyTable)
            {
                IsNullable = true
            };
            chapterPropertyTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            var orderColumn = new Column("Order", "INTEGER", chapterPropertyTable);
            chapterPropertyTable.Columns.Add("Order", orderColumn);
            orderColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(orderColumn);
            var rukusColumn = new Column("Rukus", "INTEGER", chapterPropertyTable);
            chapterPropertyTable.Columns.Add("Rukus", rukusColumn);
            rukusColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(rukusColumn);
            var startColumn = new Column("Start", "INTEGER", chapterPropertyTable);
            chapterPropertyTable.Columns.Add("Start", startColumn);
            startColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(startColumn);
            var typeColumn = new Column("Type", "TEXT", chapterPropertyTable)
            {
                IsNullable = true
            };
            chapterPropertyTable.Columns.Add("Type", typeColumn);
            typeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(typeColumn);
            relationalModel.Tables.Add(("ChapterProperty", null), chapterPropertyTable);
            var chapterPropertyTableMapping = new TableMapping(quranMetadataTable, chapterPropertyTable, null);
            chapterPropertyTable.AddTypeMapping(chapterPropertyTableMapping, false);
            tableMappings2.Add(chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, quranMetadataTable.FindProperty("Id")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(ayaColumn0, quranMetadataTable.FindProperty("Aya")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(englishNameColumn, quranMetadataTable.FindProperty("EnglishName")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(finglishNameColumn, quranMetadataTable.FindProperty("FinglishName")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, quranMetadataTable.FindProperty("Name")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(orderColumn, quranMetadataTable.FindProperty("Order")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(rukusColumn, quranMetadataTable.FindProperty("Rukus")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(startColumn, quranMetadataTable.FindProperty("Start")!, chapterPropertyTableMapping);
            RelationalModel.CreateColumnMapping(typeColumn, quranMetadataTable.FindProperty("Type")!, chapterPropertyTableMapping);
            var pK_ChapterProperty = new UniqueConstraint("PK_ChapterProperty", chapterPropertyTable, new[] { idColumn2 });
            chapterPropertyTable.PrimaryKey = pK_ChapterProperty;
            pK_ChapterProperty.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_ChapterProperty));
            var pK_ChapterPropertyKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranMetadataTable",
                new[] { "Id" });
            pK_ChapterProperty.MappedKeys.Add(pK_ChapterPropertyKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ChapterPropertyKey).Add(pK_ChapterProperty);
            chapterPropertyTable.UniqueConstraints.Add("PK_ChapterProperty", pK_ChapterProperty);

            var quranNoteTable = FindEntityType("AlAnvar.Database.Tables.QuranNoteTable")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            quranNoteTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var alAnvarDatabaseTablesQuranNoteTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranNoteTable", null, relationalModel);
            var ayaIdColumnBase1 = new ColumnBase<ColumnMappingBase>("AyaId", "INTEGER", alAnvarDatabaseTablesQuranNoteTableTableBase);
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("AyaId", ayaIdColumnBase1);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", alAnvarDatabaseTablesQuranNoteTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", alAnvarDatabaseTablesQuranNoteTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase3 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranNoteTableTableBase);
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("Id", idColumnBase3);
            var suraIdColumnBase1 = new ColumnBase<ColumnMappingBase>("SuraId", "INTEGER", alAnvarDatabaseTablesQuranNoteTableTableBase);
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("SuraId", suraIdColumnBase1);
            var titleColumnBase = new ColumnBase<ColumnMappingBase>("Title", "TEXT", alAnvarDatabaseTablesQuranNoteTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("Title", titleColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "TEXT", alAnvarDatabaseTablesQuranNoteTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranNoteTableTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranNoteTable", alAnvarDatabaseTablesQuranNoteTableTableBase);
            var alAnvarDatabaseTablesQuranNoteTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranNoteTable, alAnvarDatabaseTablesQuranNoteTableTableBase, null);
            alAnvarDatabaseTablesQuranNoteTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranNoteTableMappingBase, false);
            defaultTableMappings3.Add(alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase3, quranNoteTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaIdColumnBase1, quranNoteTable.FindProperty("AyaId")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, quranNoteTable.FindProperty("CreatedAt")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, quranNoteTable.FindProperty("Description")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)suraIdColumnBase1, quranNoteTable.FindProperty("SuraId")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)titleColumnBase, quranNoteTable.FindProperty("Title")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, quranNoteTable.FindProperty("UpdatedAt")!, alAnvarDatabaseTablesQuranNoteTableMappingBase);

            var tableMappings3 = new List<TableMapping>();
            quranNoteTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var notesTable = new Table("Notes", null, relationalModel);
            var idColumn3 = new Column("Id", "INTEGER", notesTable);
            notesTable.Columns.Add("Id", idColumn3);
            idColumn3.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn3);
            var ayaIdColumn1 = new Column("AyaId", "INTEGER", notesTable);
            notesTable.Columns.Add("AyaId", ayaIdColumn1);
            ayaIdColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(ayaIdColumn1);
            var createdAtColumn = new Column("CreatedAt", "TEXT", notesTable)
            {
                IsNullable = true
            };
            notesTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(createdAtColumn);
            var descriptionColumn = new Column("Description", "TEXT", notesTable)
            {
                IsNullable = true
            };
            notesTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var suraIdColumn1 = new Column("SuraId", "INTEGER", notesTable);
            notesTable.Columns.Add("SuraId", suraIdColumn1);
            suraIdColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(suraIdColumn1);
            var titleColumn = new Column("Title", "TEXT", notesTable)
            {
                IsNullable = true
            };
            notesTable.Columns.Add("Title", titleColumn);
            titleColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(titleColumn);
            var updatedAtColumn = new Column("UpdatedAt", "TEXT", notesTable)
            {
                IsNullable = true
            };
            notesTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(updatedAtColumn);
            relationalModel.Tables.Add(("Notes", null), notesTable);
            var notesTableMapping = new TableMapping(quranNoteTable, notesTable, null);
            notesTable.AddTypeMapping(notesTableMapping, false);
            tableMappings3.Add(notesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn3, quranNoteTable.FindProperty("Id")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(ayaIdColumn1, quranNoteTable.FindProperty("AyaId")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, quranNoteTable.FindProperty("CreatedAt")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, quranNoteTable.FindProperty("Description")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(suraIdColumn1, quranNoteTable.FindProperty("SuraId")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(titleColumn, quranNoteTable.FindProperty("Title")!, notesTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, quranNoteTable.FindProperty("UpdatedAt")!, notesTableMapping);
            var pK_Notes = new UniqueConstraint("PK_Notes", notesTable, new[] { idColumn3 });
            notesTable.PrimaryKey = pK_Notes;
            pK_Notes.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Notes));
            var pK_NotesKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranNoteTable",
                new[] { "Id" });
            pK_Notes.MappedKeys.Add(pK_NotesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_NotesKey).Add(pK_Notes);
            notesTable.UniqueConstraints.Add("PK_Notes", pK_Notes);

            var quranTable = FindEntityType("AlAnvar.Database.Tables.QuranTable")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            quranTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var alAnvarDatabaseTablesQuranTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranTable", null, relationalModel);
            var audioFileNameColumnBase0 = new ColumnBase<ColumnMappingBase>("AudioFileName", "TEXT", alAnvarDatabaseTablesQuranTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("AudioFileName", audioFileNameColumnBase0);
            var ayaColumnBase1 = new ColumnBase<ColumnMappingBase>("Aya", "TEXT", alAnvarDatabaseTablesQuranTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("Aya", ayaColumnBase1);
            var ayaIdColumnBase2 = new ColumnBase<ColumnMappingBase>("AyaId", "INTEGER", alAnvarDatabaseTablesQuranTableTableBase);
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("AyaId", ayaIdColumnBase2);
            var hizbIdColumnBase0 = new ColumnBase<ColumnMappingBase>("HizbId", "INTEGER", alAnvarDatabaseTablesQuranTableTableBase);
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("HizbId", hizbIdColumnBase0);
            var idColumnBase4 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranTableTableBase);
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("Id", idColumnBase4);
            var juzIdColumnBase0 = new ColumnBase<ColumnMappingBase>("JuzId", "INTEGER", alAnvarDatabaseTablesQuranTableTableBase);
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("JuzId", juzIdColumnBase0);
            var suraIdColumnBase2 = new ColumnBase<ColumnMappingBase>("SuraId", "INTEGER", alAnvarDatabaseTablesQuranTableTableBase);
            alAnvarDatabaseTablesQuranTableTableBase.Columns.Add("SuraId", suraIdColumnBase2);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranTable", alAnvarDatabaseTablesQuranTableTableBase);
            var alAnvarDatabaseTablesQuranTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranTable, alAnvarDatabaseTablesQuranTableTableBase, null);
            alAnvarDatabaseTablesQuranTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranTableMappingBase, false);
            defaultTableMappings4.Add(alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase4, quranTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)audioFileNameColumnBase0, quranTable.FindProperty("AudioFileName")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaColumnBase1, quranTable.FindProperty("Aya")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ayaIdColumnBase2, quranTable.FindProperty("AyaId")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hizbIdColumnBase0, quranTable.FindProperty("HizbId")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)juzIdColumnBase0, quranTable.FindProperty("JuzId")!, alAnvarDatabaseTablesQuranTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)suraIdColumnBase2, quranTable.FindProperty("SuraId")!, alAnvarDatabaseTablesQuranTableMappingBase);

            var tableMappings4 = new List<TableMapping>();
            quranTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var quranPlainTable = new Table("QuranPlain", null, relationalModel);
            var idColumn4 = new Column("Id", "INTEGER", quranPlainTable);
            quranPlainTable.Columns.Add("Id", idColumn4);
            idColumn4.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn4);
            var audioFileNameColumn0 = new Column("AudioFileName", "TEXT", quranPlainTable)
            {
                IsNullable = true
            };
            quranPlainTable.Columns.Add("AudioFileName", audioFileNameColumn0);
            audioFileNameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(audioFileNameColumn0);
            var ayaColumn1 = new Column("Aya", "TEXT", quranPlainTable)
            {
                IsNullable = true
            };
            quranPlainTable.Columns.Add("Aya", ayaColumn1);
            ayaColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ayaColumn1);
            var ayaIdColumn2 = new Column("AyaId", "INTEGER", quranPlainTable);
            quranPlainTable.Columns.Add("AyaId", ayaIdColumn2);
            ayaIdColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(ayaIdColumn2);
            var hizbIdColumn0 = new Column("HizbId", "INTEGER", quranPlainTable);
            quranPlainTable.Columns.Add("HizbId", hizbIdColumn0);
            hizbIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(hizbIdColumn0);
            var juzIdColumn0 = new Column("JuzId", "INTEGER", quranPlainTable);
            quranPlainTable.Columns.Add("JuzId", juzIdColumn0);
            juzIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(juzIdColumn0);
            var suraIdColumn2 = new Column("SuraId", "INTEGER", quranPlainTable);
            quranPlainTable.Columns.Add("SuraId", suraIdColumn2);
            suraIdColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(suraIdColumn2);
            relationalModel.Tables.Add(("QuranPlain", null), quranPlainTable);
            var quranPlainTableMapping = new TableMapping(quranTable, quranPlainTable, null);
            quranPlainTable.AddTypeMapping(quranPlainTableMapping, false);
            tableMappings4.Add(quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(idColumn4, quranTable.FindProperty("Id")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(audioFileNameColumn0, quranTable.FindProperty("AudioFileName")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(ayaColumn1, quranTable.FindProperty("Aya")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(ayaIdColumn2, quranTable.FindProperty("AyaId")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(hizbIdColumn0, quranTable.FindProperty("HizbId")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(juzIdColumn0, quranTable.FindProperty("JuzId")!, quranPlainTableMapping);
            RelationalModel.CreateColumnMapping(suraIdColumn2, quranTable.FindProperty("SuraId")!, quranPlainTableMapping);
            var pK_QuranPlain = new UniqueConstraint("PK_QuranPlain", quranPlainTable, new[] { idColumn4 });
            quranPlainTable.PrimaryKey = pK_QuranPlain;
            pK_QuranPlain.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_QuranPlain));
            var pK_QuranPlainKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranTable",
                new[] { "Id" });
            pK_QuranPlain.MappedKeys.Add(pK_QuranPlainKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_QuranPlainKey).Add(pK_QuranPlain);
            quranPlainTable.UniqueConstraints.Add("PK_QuranPlain", pK_QuranPlain);

            var quranTafsirNameTable = FindEntityType("AlAnvar.Database.Tables.QuranTafsirNameTable")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            quranTafsirNameTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var alAnvarDatabaseTablesQuranTafsirNameTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranTafsirNameTable", null, relationalModel);
            var idColumnBase5 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranTafsirNameTableTableBase);
            alAnvarDatabaseTablesQuranTafsirNameTableTableBase.Columns.Add("Id", idColumnBase5);
            var languageColumnBase = new ColumnBase<ColumnMappingBase>("Language", "TEXT", alAnvarDatabaseTablesQuranTafsirNameTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTafsirNameTableTableBase.Columns.Add("Language", languageColumnBase);
            var nameColumnBase1 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", alAnvarDatabaseTablesQuranTafsirNameTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTafsirNameTableTableBase.Columns.Add("Name", nameColumnBase1);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranTafsirNameTable", alAnvarDatabaseTablesQuranTafsirNameTableTableBase);
            var alAnvarDatabaseTablesQuranTafsirNameTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranTafsirNameTable, alAnvarDatabaseTablesQuranTafsirNameTableTableBase, null);
            alAnvarDatabaseTablesQuranTafsirNameTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranTafsirNameTableMappingBase, false);
            defaultTableMappings5.Add(alAnvarDatabaseTablesQuranTafsirNameTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase5, quranTafsirNameTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranTafsirNameTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)languageColumnBase, quranTafsirNameTable.FindProperty("Language")!, alAnvarDatabaseTablesQuranTafsirNameTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase1, quranTafsirNameTable.FindProperty("Name")!, alAnvarDatabaseTablesQuranTafsirNameTableMappingBase);

            var tableMappings5 = new List<TableMapping>();
            quranTafsirNameTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var explanationNameTable = new Table("ExplanationName", null, relationalModel);
            var idColumn5 = new Column("Id", "INTEGER", explanationNameTable);
            explanationNameTable.Columns.Add("Id", idColumn5);
            idColumn5.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn5);
            var languageColumn = new Column("Language", "TEXT", explanationNameTable)
            {
                IsNullable = true
            };
            explanationNameTable.Columns.Add("Language", languageColumn);
            languageColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(languageColumn);
            var nameColumn1 = new Column("Name", "TEXT", explanationNameTable)
            {
                IsNullable = true
            };
            explanationNameTable.Columns.Add("Name", nameColumn1);
            nameColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn1);
            relationalModel.Tables.Add(("ExplanationName", null), explanationNameTable);
            var explanationNameTableMapping = new TableMapping(quranTafsirNameTable, explanationNameTable, null);
            explanationNameTable.AddTypeMapping(explanationNameTableMapping, false);
            tableMappings5.Add(explanationNameTableMapping);
            RelationalModel.CreateColumnMapping(idColumn5, quranTafsirNameTable.FindProperty("Id")!, explanationNameTableMapping);
            RelationalModel.CreateColumnMapping(languageColumn, quranTafsirNameTable.FindProperty("Language")!, explanationNameTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn1, quranTafsirNameTable.FindProperty("Name")!, explanationNameTableMapping);
            var pK_ExplanationName = new UniqueConstraint("PK_ExplanationName", explanationNameTable, new[] { idColumn5 });
            explanationNameTable.PrimaryKey = pK_ExplanationName;
            pK_ExplanationName.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_ExplanationName));
            var pK_ExplanationNameKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranTafsirNameTable",
                new[] { "Id" });
            pK_ExplanationName.MappedKeys.Add(pK_ExplanationNameKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ExplanationNameKey).Add(pK_ExplanationName);
            explanationNameTable.UniqueConstraints.Add("PK_ExplanationName", pK_ExplanationName);

            var quranTafsirTable = FindEntityType("AlAnvar.Database.Tables.QuranTafsirTable")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            quranTafsirTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var alAnvarDatabaseTablesQuranTafsirTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranTafsirTable", null, relationalModel);
            var descriptionColumnBase0 = new ColumnBase<ColumnMappingBase>("Description", "TEXT", alAnvarDatabaseTablesQuranTafsirTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTafsirTableTableBase.Columns.Add("Description", descriptionColumnBase0);
            var explanationIdColumnBase = new ColumnBase<ColumnMappingBase>("ExplanationId", "INTEGER", alAnvarDatabaseTablesQuranTafsirTableTableBase);
            alAnvarDatabaseTablesQuranTafsirTableTableBase.Columns.Add("ExplanationId", explanationIdColumnBase);
            var idColumnBase6 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranTafsirTableTableBase);
            alAnvarDatabaseTablesQuranTafsirTableTableBase.Columns.Add("Id", idColumnBase6);
            var verseIdsColumnBase = new ColumnBase<ColumnMappingBase>("VerseIds", "TEXT", alAnvarDatabaseTablesQuranTafsirTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTafsirTableTableBase.Columns.Add("VerseIds", verseIdsColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranTafsirTable", alAnvarDatabaseTablesQuranTafsirTableTableBase);
            var alAnvarDatabaseTablesQuranTafsirTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranTafsirTable, alAnvarDatabaseTablesQuranTafsirTableTableBase, null);
            alAnvarDatabaseTablesQuranTafsirTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranTafsirTableMappingBase, false);
            defaultTableMappings6.Add(alAnvarDatabaseTablesQuranTafsirTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase6, quranTafsirTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranTafsirTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase0, quranTafsirTable.FindProperty("Description")!, alAnvarDatabaseTablesQuranTafsirTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)explanationIdColumnBase, quranTafsirTable.FindProperty("ExplanationId")!, alAnvarDatabaseTablesQuranTafsirTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)verseIdsColumnBase, quranTafsirTable.FindProperty("VerseIds")!, alAnvarDatabaseTablesQuranTafsirTableMappingBase);

            var tableMappings6 = new List<TableMapping>();
            quranTafsirTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var explanationTable = new Table("Explanation", null, relationalModel);
            var idColumn6 = new Column("Id", "INTEGER", explanationTable);
            explanationTable.Columns.Add("Id", idColumn6);
            idColumn6.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn6);
            var descriptionColumn0 = new Column("Description", "TEXT", explanationTable)
            {
                IsNullable = true
            };
            explanationTable.Columns.Add("Description", descriptionColumn0);
            descriptionColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn0);
            var explanationIdColumn = new Column("ExplanationId", "INTEGER", explanationTable);
            explanationTable.Columns.Add("ExplanationId", explanationIdColumn);
            explanationIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(explanationIdColumn);
            var verseIdsColumn = new Column("VerseIds", "TEXT", explanationTable)
            {
                IsNullable = true
            };
            explanationTable.Columns.Add("VerseIds", verseIdsColumn);
            verseIdsColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(verseIdsColumn);
            relationalModel.Tables.Add(("Explanation", null), explanationTable);
            var explanationTableMapping = new TableMapping(quranTafsirTable, explanationTable, null);
            explanationTable.AddTypeMapping(explanationTableMapping, false);
            tableMappings6.Add(explanationTableMapping);
            RelationalModel.CreateColumnMapping(idColumn6, quranTafsirTable.FindProperty("Id")!, explanationTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn0, quranTafsirTable.FindProperty("Description")!, explanationTableMapping);
            RelationalModel.CreateColumnMapping(explanationIdColumn, quranTafsirTable.FindProperty("ExplanationId")!, explanationTableMapping);
            RelationalModel.CreateColumnMapping(verseIdsColumn, quranTafsirTable.FindProperty("VerseIds")!, explanationTableMapping);
            var pK_Explanation = new UniqueConstraint("PK_Explanation", explanationTable, new[] { idColumn6 });
            explanationTable.PrimaryKey = pK_Explanation;
            pK_Explanation.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Explanation));
            var pK_ExplanationKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranTafsirTable",
                new[] { "Id" });
            pK_Explanation.MappedKeys.Add(pK_ExplanationKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ExplanationKey).Add(pK_Explanation);
            explanationTable.UniqueConstraints.Add("PK_Explanation", pK_Explanation);

            var quranTranslationTable = FindEntityType("AlAnvar.Database.Tables.QuranTranslationTable")!;

            var defaultTableMappings7 = new List<TableMappingBase<ColumnMappingBase>>();
            quranTranslationTable.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings7);
            var alAnvarDatabaseTablesQuranTranslationTableTableBase = new TableBase("AlAnvar.Database.Tables.QuranTranslationTable", null, relationalModel);
            var idColumnBase7 = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", alAnvarDatabaseTablesQuranTranslationTableTableBase);
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("Id", idColumnBase7);
            var isActiveColumnBase0 = new ColumnBase<ColumnMappingBase>("IsActive", "INTEGER", alAnvarDatabaseTablesQuranTranslationTableTableBase);
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("IsActive", isActiveColumnBase0);
            var languageColumnBase0 = new ColumnBase<ColumnMappingBase>("Language", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("Language", languageColumnBase0);
            var linkColumnBase = new ColumnBase<ColumnMappingBase>("Link", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("Link", linkColumnBase);
            var nameColumnBase2 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("Name", nameColumnBase2);
            var originalLinkColumnBase = new ColumnBase<ColumnMappingBase>("OriginalLink", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("OriginalLink", originalLinkColumnBase);
            var translationIdColumnBase = new ColumnBase<ColumnMappingBase>("TranslationId", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("TranslationId", translationIdColumnBase);
            var translatorColumnBase = new ColumnBase<ColumnMappingBase>("Translator", "TEXT", alAnvarDatabaseTablesQuranTranslationTableTableBase)
            {
                IsNullable = true
            };
            alAnvarDatabaseTablesQuranTranslationTableTableBase.Columns.Add("Translator", translatorColumnBase);
            relationalModel.DefaultTables.Add("AlAnvar.Database.Tables.QuranTranslationTable", alAnvarDatabaseTablesQuranTranslationTableTableBase);
            var alAnvarDatabaseTablesQuranTranslationTableMappingBase = new TableMappingBase<ColumnMappingBase>(quranTranslationTable, alAnvarDatabaseTablesQuranTranslationTableTableBase, null);
            alAnvarDatabaseTablesQuranTranslationTableTableBase.AddTypeMapping(alAnvarDatabaseTablesQuranTranslationTableMappingBase, false);
            defaultTableMappings7.Add(alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase7, quranTranslationTable.FindProperty("Id")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isActiveColumnBase0, quranTranslationTable.FindProperty("IsActive")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)languageColumnBase0, quranTranslationTable.FindProperty("Language")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)linkColumnBase, quranTranslationTable.FindProperty("Link")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase2, quranTranslationTable.FindProperty("Name")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)originalLinkColumnBase, quranTranslationTable.FindProperty("OriginalLink")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)translationIdColumnBase, quranTranslationTable.FindProperty("TranslationId")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)translatorColumnBase, quranTranslationTable.FindProperty("Translator")!, alAnvarDatabaseTablesQuranTranslationTableMappingBase);

            var tableMappings7 = new List<TableMapping>();
            quranTranslationTable.SetRuntimeAnnotation("Relational:TableMappings", tableMappings7);
            var translationsTable = new Table("Translations", null, relationalModel);
            var idColumn7 = new Column("Id", "INTEGER", translationsTable);
            translationsTable.Columns.Add("Id", idColumn7);
            idColumn7.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn7);
            var isActiveColumn0 = new Column("IsActive", "INTEGER", translationsTable);
            translationsTable.Columns.Add("IsActive", isActiveColumn0);
            isActiveColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isActiveColumn0);
            var languageColumn0 = new Column("Language", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("Language", languageColumn0);
            languageColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(languageColumn0);
            var linkColumn = new Column("Link", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("Link", linkColumn);
            linkColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(linkColumn);
            var nameColumn2 = new Column("Name", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("Name", nameColumn2);
            nameColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn2);
            var originalLinkColumn = new Column("OriginalLink", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("OriginalLink", originalLinkColumn);
            originalLinkColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(originalLinkColumn);
            var translationIdColumn = new Column("TranslationId", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("TranslationId", translationIdColumn);
            translationIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(translationIdColumn);
            var translatorColumn = new Column("Translator", "TEXT", translationsTable)
            {
                IsNullable = true
            };
            translationsTable.Columns.Add("Translator", translatorColumn);
            translatorColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(translatorColumn);
            relationalModel.Tables.Add(("Translations", null), translationsTable);
            var translationsTableMapping = new TableMapping(quranTranslationTable, translationsTable, null);
            translationsTable.AddTypeMapping(translationsTableMapping, false);
            tableMappings7.Add(translationsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn7, quranTranslationTable.FindProperty("Id")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(isActiveColumn0, quranTranslationTable.FindProperty("IsActive")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(languageColumn0, quranTranslationTable.FindProperty("Language")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(linkColumn, quranTranslationTable.FindProperty("Link")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn2, quranTranslationTable.FindProperty("Name")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(originalLinkColumn, quranTranslationTable.FindProperty("OriginalLink")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(translationIdColumn, quranTranslationTable.FindProperty("TranslationId")!, translationsTableMapping);
            RelationalModel.CreateColumnMapping(translatorColumn, quranTranslationTable.FindProperty("Translator")!, translationsTableMapping);
            var pK_Translations = new UniqueConstraint("PK_Translations", translationsTable, new[] { idColumn7 });
            translationsTable.PrimaryKey = pK_Translations;
            pK_Translations.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Translations));
            var pK_TranslationsKey = RelationalModel.GetKey(this,
                "AlAnvar.Database.Tables.QuranTranslationTable",
                new[] { "Id" });
            pK_Translations.MappedKeys.Add(pK_TranslationsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_TranslationsKey).Add(pK_Translations);
            translationsTable.UniqueConstraints.Add("PK_Translations", pK_Translations);
            return relationalModel.MakeReadOnly();
        }
    }
}
