// <auto-generated />
using AlAnvar.Database;
using AlAnvar.Database.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AlAnvarDBContext), typeof(AlAnvarDBContextModel))]
