// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranTafsirTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranTafsirTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(QuranTafsirTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExplanationId>k__BackingField")]
        public static extern ref int ExplanationId(QuranTafsirTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<VerseIds>k__BackingField")]
        public static extern ref string VerseIds(QuranTafsirTable @this);
    }
}
