// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranTable",
                typeof(QuranTable),
                baseEntityType,
                propertyCount: 7,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranTable instance) => QuranTableUnsafeAccessors.Id(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranTableUnsafeAccessors.Id(((QuranTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranTableUnsafeAccessors.Id(((QuranTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.Id(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var audioFileName = runtimeEntityType.AddProperty(
                "AudioFileName",
                typeof(string),
                propertyInfo: typeof(QuranTable).GetProperty("AudioFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<AudioFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            audioFileName.SetGetter(
                string (QuranTable instance) => QuranTableUnsafeAccessors.AudioFileName(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.AudioFileName(instance) == null);
            audioFileName.SetSetter(
                QuranTable (QuranTable instance, string value) =>
                {
                    QuranTableUnsafeAccessors.AudioFileName(instance) = value;
                    return instance;
                });
            audioFileName.SetMaterializationSetter(
                QuranTable (QuranTable instance, string value) =>
                {
                    QuranTableUnsafeAccessors.AudioFileName(instance) = value;
                    return instance;
                });
            audioFileName.SetAccessors(
                string (IInternalEntry entry) => QuranTableUnsafeAccessors.AudioFileName(((QuranTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTableUnsafeAccessors.AudioFileName(((QuranTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(audioFileName, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(audioFileName));
            audioFileName.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            audioFileName.TypeMapping = SqliteStringTypeMapping.Default;

            var aya = runtimeEntityType.AddProperty(
                "Aya",
                typeof(string),
                propertyInfo: typeof(QuranTable).GetProperty("Aya", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<Aya>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            aya.SetGetter(
                string (QuranTable instance) => QuranTableUnsafeAccessors.Aya(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.Aya(instance) == null);
            aya.SetSetter(
                QuranTable (QuranTable instance, string value) =>
                {
                    QuranTableUnsafeAccessors.Aya(instance) = value;
                    return instance;
                });
            aya.SetMaterializationSetter(
                QuranTable (QuranTable instance, string value) =>
                {
                    QuranTableUnsafeAccessors.Aya(instance) = value;
                    return instance;
                });
            aya.SetAccessors(
                string (IInternalEntry entry) => QuranTableUnsafeAccessors.Aya(((QuranTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTableUnsafeAccessors.Aya(((QuranTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(aya, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(aya));
            aya.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            aya.TypeMapping = SqliteStringTypeMapping.Default;

            var ayaId = runtimeEntityType.AddProperty(
                "AyaId",
                typeof(int),
                propertyInfo: typeof(QuranTable).GetProperty("AyaId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<AyaId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            ayaId.SetGetter(
                int (QuranTable instance) => QuranTableUnsafeAccessors.AyaId(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.AyaId(instance) == 0);
            ayaId.SetSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetMaterializationSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetAccessors(
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.AyaId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.AyaId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(ayaId, 3),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(ayaId));
            ayaId.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ayaId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var hizbId = runtimeEntityType.AddProperty(
                "HizbId",
                typeof(int),
                propertyInfo: typeof(QuranTable).GetProperty("HizbId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<HizbId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            hizbId.SetGetter(
                int (QuranTable instance) => QuranTableUnsafeAccessors.HizbId(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.HizbId(instance) == 0);
            hizbId.SetSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.HizbId(instance) = value;
                    return instance;
                });
            hizbId.SetMaterializationSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.HizbId(instance) = value;
                    return instance;
                });
            hizbId.SetAccessors(
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.HizbId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.HizbId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(hizbId, 4),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(hizbId));
            hizbId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            hizbId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var juzId = runtimeEntityType.AddProperty(
                "JuzId",
                typeof(int),
                propertyInfo: typeof(QuranTable).GetProperty("JuzId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<JuzId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            juzId.SetGetter(
                int (QuranTable instance) => QuranTableUnsafeAccessors.JuzId(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.JuzId(instance) == 0);
            juzId.SetSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.JuzId(instance) = value;
                    return instance;
                });
            juzId.SetMaterializationSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.JuzId(instance) = value;
                    return instance;
                });
            juzId.SetAccessors(
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.JuzId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.JuzId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(juzId, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(juzId));
            juzId.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            juzId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var suraId = runtimeEntityType.AddProperty(
                "SuraId",
                typeof(int),
                propertyInfo: typeof(QuranTable).GetProperty("SuraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTable).GetField("<SuraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            suraId.SetGetter(
                int (QuranTable instance) => QuranTableUnsafeAccessors.SuraId(instance),
                bool (QuranTable instance) => QuranTableUnsafeAccessors.SuraId(instance) == 0);
            suraId.SetSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetMaterializationSetter(
                QuranTable (QuranTable instance, int value) =>
                {
                    QuranTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetAccessors(
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.SuraId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranTableUnsafeAccessors.SuraId(((QuranTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(suraId, 6),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(suraId));
            suraId.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            suraId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var audioFileName = runtimeEntityType.FindProperty("AudioFileName");
            var aya = runtimeEntityType.FindProperty("Aya");
            var ayaId = runtimeEntityType.FindProperty("AyaId");
            var hizbId = runtimeEntityType.FindProperty("HizbId");
            var juzId = runtimeEntityType.FindProperty("JuzId");
            var suraId = runtimeEntityType.FindProperty("SuraId");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, string, int, int, int, int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(audioFileName) == null ? null : ((ValueComparer<string>)(((IProperty)audioFileName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(audioFileName))), (source.GetCurrentValue<string>(aya) == null ? null : ((ValueComparer<string>)(((IProperty)aya).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(aya))), ((ValueComparer<int>)(((IProperty)ayaId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(ayaId)), ((ValueComparer<int>)(((IProperty)hizbId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(hizbId)), ((ValueComparer<int>)(((IProperty)juzId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(juzId)), ((ValueComparer<int>)(((IProperty)suraId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(suraId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "QuranPlain");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
