// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranTafsirTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranTafsirTable",
                typeof(QuranTafsirTable),
                baseEntityType,
                propertyCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranTafsirTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTafsirTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.Id(instance),
                bool (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranTafsirTable (QuranTafsirTable instance, int value) =>
                {
                    QuranTafsirTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranTafsirTable (QuranTafsirTable instance, int value) =>
                {
                    QuranTafsirTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranTafsirTableUnsafeAccessors.Id(((QuranTafsirTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranTafsirTableUnsafeAccessors.Id(((QuranTafsirTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.Id(((QuranTafsirTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(QuranTafsirTable).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTafsirTable).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            description.SetGetter(
                string (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.Description(instance),
                bool (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                QuranTafsirTable (QuranTafsirTable instance, string value) =>
                {
                    QuranTafsirTableUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                QuranTafsirTable (QuranTafsirTable instance, string value) =>
                {
                    QuranTafsirTableUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.Description(((QuranTafsirTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.Description(((QuranTafsirTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var explanationId = runtimeEntityType.AddProperty(
                "ExplanationId",
                typeof(int),
                propertyInfo: typeof(QuranTafsirTable).GetProperty("ExplanationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTafsirTable).GetField("<ExplanationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            explanationId.SetGetter(
                int (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.ExplanationId(instance),
                bool (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.ExplanationId(instance) == 0);
            explanationId.SetSetter(
                QuranTafsirTable (QuranTafsirTable instance, int value) =>
                {
                    QuranTafsirTableUnsafeAccessors.ExplanationId(instance) = value;
                    return instance;
                });
            explanationId.SetMaterializationSetter(
                QuranTafsirTable (QuranTafsirTable instance, int value) =>
                {
                    QuranTafsirTableUnsafeAccessors.ExplanationId(instance) = value;
                    return instance;
                });
            explanationId.SetAccessors(
                int (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.ExplanationId(((QuranTafsirTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.ExplanationId(((QuranTafsirTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(explanationId, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(explanationId));
            explanationId.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            explanationId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var verseIds = runtimeEntityType.AddProperty(
                "VerseIds",
                typeof(string),
                propertyInfo: typeof(QuranTafsirTable).GetProperty("VerseIds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTafsirTable).GetField("<VerseIds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            verseIds.SetGetter(
                string (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.VerseIds(instance),
                bool (QuranTafsirTable instance) => QuranTafsirTableUnsafeAccessors.VerseIds(instance) == null);
            verseIds.SetSetter(
                QuranTafsirTable (QuranTafsirTable instance, string value) =>
                {
                    QuranTafsirTableUnsafeAccessors.VerseIds(instance) = value;
                    return instance;
                });
            verseIds.SetMaterializationSetter(
                QuranTafsirTable (QuranTafsirTable instance, string value) =>
                {
                    QuranTafsirTableUnsafeAccessors.VerseIds(instance) = value;
                    return instance;
                });
            verseIds.SetAccessors(
                string (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.VerseIds(((QuranTafsirTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTafsirTableUnsafeAccessors.VerseIds(((QuranTafsirTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(verseIds, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(verseIds));
            verseIds.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            verseIds.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var description = runtimeEntityType.FindProperty("Description");
            var explanationId = runtimeEntityType.FindProperty("ExplanationId");
            var verseIds = runtimeEntityType.FindProperty("VerseIds");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTafsirTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<int>)(((IProperty)explanationId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(explanationId)), (source.GetCurrentValue<string>(verseIds) == null ? null : ((ValueComparer<string>)(((IProperty)verseIds).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(verseIds))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTafsirTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Explanation");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
