// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranFavoriteTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranFavoriteTable",
                typeof(QuranFavoriteTable),
                baseEntityType,
                propertyCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranFavoriteTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranFavoriteTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.Id(instance),
                bool (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranFavoriteTableUnsafeAccessors.Id(((QuranFavoriteTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranFavoriteTableUnsafeAccessors.Id(((QuranFavoriteTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranFavoriteTableUnsafeAccessors.Id(((QuranFavoriteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var ayaId = runtimeEntityType.AddProperty(
                "AyaId",
                typeof(int),
                propertyInfo: typeof(QuranFavoriteTable).GetProperty("AyaId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranFavoriteTable).GetField("<AyaId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            ayaId.SetGetter(
                int (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.AyaId(instance),
                bool (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.AyaId(instance) == 0);
            ayaId.SetSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetMaterializationSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetAccessors(
                int (IInternalEntry entry) => QuranFavoriteTableUnsafeAccessors.AyaId(((QuranFavoriteTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranFavoriteTableUnsafeAccessors.AyaId(((QuranFavoriteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(ayaId, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(ayaId));
            ayaId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ayaId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var suraId = runtimeEntityType.AddProperty(
                "SuraId",
                typeof(int),
                propertyInfo: typeof(QuranFavoriteTable).GetProperty("SuraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranFavoriteTable).GetField("<SuraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            suraId.SetGetter(
                int (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.SuraId(instance),
                bool (QuranFavoriteTable instance) => QuranFavoriteTableUnsafeAccessors.SuraId(instance) == 0);
            suraId.SetSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetMaterializationSetter(
                QuranFavoriteTable (QuranFavoriteTable instance, int value) =>
                {
                    QuranFavoriteTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetAccessors(
                int (IInternalEntry entry) => QuranFavoriteTableUnsafeAccessors.SuraId(((QuranFavoriteTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranFavoriteTableUnsafeAccessors.SuraId(((QuranFavoriteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(suraId, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(suraId));
            suraId.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            suraId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var ayaId = runtimeEntityType.FindProperty("AyaId");
            var suraId = runtimeEntityType.FindProperty("SuraId");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranFavoriteTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int, int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)ayaId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(ayaId)), ((ValueComparer<int>)(((IProperty)suraId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(suraId)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranFavoriteTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 3,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 3,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Favorites");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
