// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranAudioTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranAudioTable",
                typeof(QuranAudioTable),
                baseEntityType,
                propertyCount: 6,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranAudioTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Id(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranAudioTable (QuranAudioTable instance, int value) =>
                {
                    QuranAudioTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, int value) =>
                {
                    QuranAudioTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranAudioTableUnsafeAccessors.Id(((QuranAudioTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranAudioTableUnsafeAccessors.Id(((QuranAudioTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.Id(((QuranAudioTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var dirName = runtimeEntityType.AddProperty(
                "DirName",
                typeof(string),
                propertyInfo: typeof(QuranAudioTable).GetProperty("DirName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<DirName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            dirName.SetGetter(
                string (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.DirName(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.DirName(instance) == null);
            dirName.SetSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.DirName(instance) = value;
                    return instance;
                });
            dirName.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.DirName(instance) = value;
                    return instance;
                });
            dirName.SetAccessors(
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.DirName(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.DirName(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(dirName, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(dirName));
            dirName.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            dirName.TypeMapping = SqliteStringTypeMapping.Default;

            var isActive = runtimeEntityType.AddProperty(
                "IsActive",
                typeof(bool),
                propertyInfo: typeof(QuranAudioTable).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isActive.SetGetter(
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.IsActive(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.IsActive(instance) == false);
            isActive.SetSetter(
                QuranAudioTable (QuranAudioTable instance, bool value) =>
                {
                    QuranAudioTableUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, bool value) =>
                {
                    QuranAudioTableUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetAccessors(
                bool (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.IsActive(((QuranAudioTable)(entry.Entity))),
                bool (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.IsActive(((QuranAudioTable)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 2),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
            isActive.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isActive.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(QuranAudioTable).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            name.SetGetter(
                string (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Name(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.Name(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.Name(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var persianName = runtimeEntityType.AddProperty(
                "PersianName",
                typeof(string),
                propertyInfo: typeof(QuranAudioTable).GetProperty("PersianName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<PersianName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            persianName.SetGetter(
                string (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.PersianName(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.PersianName(instance) == null);
            persianName.SetSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.PersianName(instance) = value;
                    return instance;
                });
            persianName.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.PersianName(instance) = value;
                    return instance;
                });
            persianName.SetAccessors(
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.PersianName(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.PersianName(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(persianName, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(persianName));
            persianName.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            persianName.TypeMapping = SqliteStringTypeMapping.Default;

            var url = runtimeEntityType.AddProperty(
                "Url",
                typeof(string),
                propertyInfo: typeof(QuranAudioTable).GetProperty("Url", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranAudioTable).GetField("<Url>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            url.SetGetter(
                string (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Url(instance),
                bool (QuranAudioTable instance) => QuranAudioTableUnsafeAccessors.Url(instance) == null);
            url.SetSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.Url(instance) = value;
                    return instance;
                });
            url.SetMaterializationSetter(
                QuranAudioTable (QuranAudioTable instance, string value) =>
                {
                    QuranAudioTableUnsafeAccessors.Url(instance) = value;
                    return instance;
                });
            url.SetAccessors(
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.Url(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranAudioTableUnsafeAccessors.Url(((QuranAudioTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(url, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(url));
            url.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            url.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var dirName = runtimeEntityType.FindProperty("DirName");
            var isActive = runtimeEntityType.FindProperty("IsActive");
            var name = runtimeEntityType.FindProperty("Name");
            var persianName = runtimeEntityType.FindProperty("PersianName");
            var url = runtimeEntityType.FindProperty("Url");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranAudioTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string, bool, string, string, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(dirName) == null ? null : ((ValueComparer<string>)(((IProperty)dirName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(dirName))), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(persianName) == null ? null : ((ValueComparer<string>)(((IProperty)persianName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(persianName))), (source.GetCurrentValue<string>(url) == null ? null : ((ValueComparer<string>)(((IProperty)url).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(url))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranAudioTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Audio");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
