// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranMetadataTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranMetadataTable",
                typeof(QuranMetadataTable),
                baseEntityType,
                propertyCount: 9,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Id(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranMetadataTableUnsafeAccessors.Id(((QuranMetadataTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranMetadataTableUnsafeAccessors.Id(((QuranMetadataTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Id(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var aya = runtimeEntityType.AddProperty(
                "Aya",
                typeof(int),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Aya", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Aya>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            aya.SetGetter(
                int (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Aya(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Aya(instance) == 0);
            aya.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Aya(instance) = value;
                    return instance;
                });
            aya.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Aya(instance) = value;
                    return instance;
                });
            aya.SetAccessors(
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Aya(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Aya(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(aya, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(aya));
            aya.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            aya.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var englishName = runtimeEntityType.AddProperty(
                "EnglishName",
                typeof(string),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("EnglishName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<EnglishName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            englishName.SetGetter(
                string (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.EnglishName(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.EnglishName(instance) == null);
            englishName.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.EnglishName(instance) = value;
                    return instance;
                });
            englishName.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.EnglishName(instance) = value;
                    return instance;
                });
            englishName.SetAccessors(
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.EnglishName(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.EnglishName(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(englishName, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(englishName));
            englishName.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            englishName.TypeMapping = SqliteStringTypeMapping.Default;

            var finglishName = runtimeEntityType.AddProperty(
                "FinglishName",
                typeof(string),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("FinglishName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<FinglishName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            finglishName.SetGetter(
                string (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.FinglishName(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.FinglishName(instance) == null);
            finglishName.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.FinglishName(instance) = value;
                    return instance;
                });
            finglishName.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.FinglishName(instance) = value;
                    return instance;
                });
            finglishName.SetAccessors(
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.FinglishName(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.FinglishName(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(finglishName, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(finglishName));
            finglishName.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            finglishName.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            name.SetGetter(
                string (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Name(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Name(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Name(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var order = runtimeEntityType.AddProperty(
                "Order",
                typeof(int),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Order", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Order>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            order.SetGetter(
                int (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Order(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Order(instance) == 0);
            order.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Order(instance) = value;
                    return instance;
                });
            order.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Order(instance) = value;
                    return instance;
                });
            order.SetAccessors(
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Order(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Order(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(order, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(order));
            order.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            order.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var rukus = runtimeEntityType.AddProperty(
                "Rukus",
                typeof(int),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Rukus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Rukus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            rukus.SetGetter(
                int (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Rukus(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Rukus(instance) == 0);
            rukus.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Rukus(instance) = value;
                    return instance;
                });
            rukus.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Rukus(instance) = value;
                    return instance;
                });
            rukus.SetAccessors(
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Rukus(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Rukus(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(rukus, 6),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(rukus));
            rukus.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            rukus.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var start = runtimeEntityType.AddProperty(
                "Start",
                typeof(int),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Start", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Start>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            start.SetGetter(
                int (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Start(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Start(instance) == 0);
            start.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Start(instance) = value;
                    return instance;
                });
            start.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, int value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Start(instance) = value;
                    return instance;
                });
            start.SetAccessors(
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Start(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Start(((QuranMetadataTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(start, 7),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(start));
            start.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            start.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(string),
                propertyInfo: typeof(QuranMetadataTable).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranMetadataTable).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            type.SetGetter(
                string (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Type(instance),
                bool (QuranMetadataTable instance) => QuranMetadataTableUnsafeAccessors.Type(instance) == null);
            type.SetSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Type(instance) = value;
                    return instance;
                });
            type.SetMaterializationSetter(
                QuranMetadataTable (QuranMetadataTable instance, string value) =>
                {
                    QuranMetadataTableUnsafeAccessors.Type(instance) = value;
                    return instance;
                });
            type.SetAccessors(
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Type(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranMetadataTableUnsafeAccessors.Type(((QuranMetadataTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(type, 8),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(type));
            type.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            type.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var aya = runtimeEntityType.FindProperty("Aya");
            var englishName = runtimeEntityType.FindProperty("EnglishName");
            var finglishName = runtimeEntityType.FindProperty("FinglishName");
            var name = runtimeEntityType.FindProperty("Name");
            var order = runtimeEntityType.FindProperty("Order");
            var rukus = runtimeEntityType.FindProperty("Rukus");
            var start = runtimeEntityType.FindProperty("Start");
            var type = runtimeEntityType.FindProperty("Type");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranMetadataTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int, string, string, string, int, int, int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)aya).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(aya)), (source.GetCurrentValue<string>(englishName) == null ? null : ((ValueComparer<string>)(((IProperty)englishName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(englishName))), (source.GetCurrentValue<string>(finglishName) == null ? null : ((ValueComparer<string>)(((IProperty)finglishName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(finglishName))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), ((ValueComparer<int>)(((IProperty)order).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(order)), ((ValueComparer<int>)(((IProperty)rukus).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(rukus)), ((ValueComparer<int>)(((IProperty)start).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(start)), (source.GetCurrentValue<string>(type) == null ? null : ((ValueComparer<string>)(((IProperty)type).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(type))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranMetadataTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 9,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 9,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ChapterProperty");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
