// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranAudioTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranAudioTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DirName>k__BackingField")]
        public static extern ref string DirName(QuranAudioTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(QuranAudioTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(QuranAudioTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PersianName>k__BackingField")]
        public static extern ref string PersianName(QuranAudioTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Url>k__BackingField")]
        public static extern ref string Url(QuranAudioTable @this);
    }
}
