// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranNoteTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranNoteTable",
                typeof(QuranNoteTable),
                baseEntityType,
                propertyCount: 7,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranNoteTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Id(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranNoteTableUnsafeAccessors.Id(((QuranNoteTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranNoteTableUnsafeAccessors.Id(((QuranNoteTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.Id(((QuranNoteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var ayaId = runtimeEntityType.AddProperty(
                "AyaId",
                typeof(int),
                propertyInfo: typeof(QuranNoteTable).GetProperty("AyaId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<AyaId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            ayaId.SetGetter(
                int (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.AyaId(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.AyaId(instance) == 0);
            ayaId.SetSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.AyaId(instance) = value;
                    return instance;
                });
            ayaId.SetAccessors(
                int (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.AyaId(((QuranNoteTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.AyaId(((QuranNoteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(ayaId, 1),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(ayaId));
            ayaId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ayaId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(string),
                propertyInfo: typeof(QuranNoteTable).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            createdAt.SetGetter(
                string (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.CreatedAt(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.CreatedAt(instance) == null);
            createdAt.SetSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.CreatedAt(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.CreatedAt(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(createdAt, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteStringTypeMapping.Default;

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(QuranNoteTable).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            description.SetGetter(
                string (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Description(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.Description(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.Description(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var suraId = runtimeEntityType.AddProperty(
                "SuraId",
                typeof(int),
                propertyInfo: typeof(QuranNoteTable).GetProperty("SuraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<SuraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            suraId.SetGetter(
                int (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.SuraId(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.SuraId(instance) == 0);
            suraId.SetSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, int value) =>
                {
                    QuranNoteTableUnsafeAccessors.SuraId(instance) = value;
                    return instance;
                });
            suraId.SetAccessors(
                int (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.SuraId(((QuranNoteTable)(entry.Entity))),
                int (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.SuraId(((QuranNoteTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(suraId, 4),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(suraId));
            suraId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            suraId.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(QuranNoteTable).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            title.SetGetter(
                string (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Title(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.Title(instance) == null);
            title.SetSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.Title(instance) = value;
                    return instance;
                });
            title.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.Title(instance) = value;
                    return instance;
                });
            title.SetAccessors(
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.Title(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.Title(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(title, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(title));
            title.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            title.TypeMapping = SqliteStringTypeMapping.Default;

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(string),
                propertyInfo: typeof(QuranNoteTable).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranNoteTable).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            updatedAt.SetGetter(
                string (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.UpdatedAt(instance),
                bool (QuranNoteTable instance) => QuranNoteTableUnsafeAccessors.UpdatedAt(instance) == null);
            updatedAt.SetSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetMaterializationSetter(
                QuranNoteTable (QuranNoteTable instance, string value) =>
                {
                    QuranNoteTableUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetAccessors(
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.UpdatedAt(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranNoteTableUnsafeAccessors.UpdatedAt(((QuranNoteTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(updatedAt, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(updatedAt));
            updatedAt.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAt.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var ayaId = runtimeEntityType.FindProperty("AyaId");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var description = runtimeEntityType.FindProperty("Description");
            var suraId = runtimeEntityType.FindProperty("SuraId");
            var title = runtimeEntityType.FindProperty("Title");
            var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranNoteTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, int, string, string, int, string, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<int>)(((IProperty)ayaId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(ayaId)), (source.GetCurrentValue<string>(createdAt) == null ? null : ((ValueComparer<string>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(createdAt))), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<int>)(((IProperty)suraId).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(suraId)), (source.GetCurrentValue<string>(title) == null ? null : ((ValueComparer<string>)(((IProperty)title).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(title))), (source.GetCurrentValue<string>(updatedAt) == null ? null : ((ValueComparer<string>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(updatedAt))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranNoteTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Notes");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
