// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranNoteTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AyaId>k__BackingField")]
        public static extern ref int AyaId(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref string CreatedAt(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SuraId>k__BackingField")]
        public static extern ref int SuraId(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(QuranNoteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref string UpdatedAt(QuranNoteTable @this);
    }
}
