// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranFavoriteTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranFavoriteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AyaId>k__BackingField")]
        public static extern ref int AyaId(QuranFavoriteTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SuraId>k__BackingField")]
        public static extern ref int SuraId(QuranFavoriteTable @this);
    }
}
