// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranTranslationTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Language>k__BackingField")]
        public static extern ref string Language(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Link>k__BackingField")]
        public static extern ref string Link(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginalLink>k__BackingField")]
        public static extern ref string OriginalLink(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TranslationId>k__BackingField")]
        public static extern ref string TranslationId(QuranTranslationTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Translator>k__BackingField")]
        public static extern ref string Translator(QuranTranslationTable @this);
    }
}
