// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranMetadataTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Aya>k__BackingField")]
        public static extern ref int Aya(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EnglishName>k__BackingField")]
        public static extern ref string EnglishName(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FinglishName>k__BackingField")]
        public static extern ref string FinglishName(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Order>k__BackingField")]
        public static extern ref int Order(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Rukus>k__BackingField")]
        public static extern ref int Rukus(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Start>k__BackingField")]
        public static extern ref int Start(QuranMetadataTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref string Type(QuranMetadataTable @this);
    }
}
