// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using AlAnvar.Database.Tables;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class QuranTranslationTableEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "AlAnvar.Database.Tables.QuranTranslationTable",
                typeof(QuranTranslationTable),
                baseEntityType,
                propertyCount: 8,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Id(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Id(instance) == 0);
            id.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, int value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, int value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<int>(0) : (entry.FlaggedAsTemporary(0) && QuranTranslationTableUnsafeAccessors.Id(((QuranTranslationTable)(entry.Entity))) == 0 ? entry.ReadTemporaryValue<int>(0) : QuranTranslationTableUnsafeAccessors.Id(((QuranTranslationTable)(entry.Entity))))),
                int (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Id(((QuranTranslationTable)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));

            var isActive = runtimeEntityType.AddProperty(
                "IsActive",
                typeof(bool),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isActive.SetGetter(
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.IsActive(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.IsActive(instance) == false);
            isActive.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, bool value) =>
                {
                    QuranTranslationTableUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, bool value) =>
                {
                    QuranTranslationTableUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetAccessors(
                bool (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.IsActive(((QuranTranslationTable)(entry.Entity))),
                bool (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.IsActive(((QuranTranslationTable)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 1),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
            isActive.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isActive.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var language = runtimeEntityType.AddProperty(
                "Language",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("Language", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<Language>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            language.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Language(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Language(instance) == null);
            language.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Language(instance) = value;
                    return instance;
                });
            language.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Language(instance) = value;
                    return instance;
                });
            language.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Language(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Language(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(language, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(language));
            language.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            language.TypeMapping = SqliteStringTypeMapping.Default;

            var link = runtimeEntityType.AddProperty(
                "Link",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("Link", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<Link>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            link.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Link(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Link(instance) == null);
            link.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Link(instance) = value;
                    return instance;
                });
            link.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Link(instance) = value;
                    return instance;
                });
            link.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Link(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Link(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(link, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(link));
            link.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            link.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            name.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Name(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Name(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Name(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var originalLink = runtimeEntityType.AddProperty(
                "OriginalLink",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("OriginalLink", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<OriginalLink>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            originalLink.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.OriginalLink(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.OriginalLink(instance) == null);
            originalLink.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.OriginalLink(instance) = value;
                    return instance;
                });
            originalLink.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.OriginalLink(instance) = value;
                    return instance;
                });
            originalLink.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.OriginalLink(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.OriginalLink(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(originalLink, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(originalLink));
            originalLink.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            originalLink.TypeMapping = SqliteStringTypeMapping.Default;

            var translationId = runtimeEntityType.AddProperty(
                "TranslationId",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("TranslationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<TranslationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            translationId.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.TranslationId(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.TranslationId(instance) == null);
            translationId.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.TranslationId(instance) = value;
                    return instance;
                });
            translationId.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.TranslationId(instance) = value;
                    return instance;
                });
            translationId.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.TranslationId(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.TranslationId(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(translationId, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(translationId));
            translationId.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            translationId.TypeMapping = SqliteStringTypeMapping.Default;

            var translator = runtimeEntityType.AddProperty(
                "Translator",
                typeof(string),
                propertyInfo: typeof(QuranTranslationTable).GetProperty("Translator", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(QuranTranslationTable).GetField("<Translator>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            translator.SetGetter(
                string (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Translator(instance),
                bool (QuranTranslationTable instance) => QuranTranslationTableUnsafeAccessors.Translator(instance) == null);
            translator.SetSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Translator(instance) = value;
                    return instance;
                });
            translator.SetMaterializationSetter(
                QuranTranslationTable (QuranTranslationTable instance, string value) =>
                {
                    QuranTranslationTableUnsafeAccessors.Translator(instance) = value;
                    return instance;
                });
            translator.SetAccessors(
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Translator(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => QuranTranslationTableUnsafeAccessors.Translator(((QuranTranslationTable)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(translator, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(translator));
            translator.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            translator.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var isActive = runtimeEntityType.FindProperty("IsActive");
            var language = runtimeEntityType.FindProperty("Language");
            var link = runtimeEntityType.FindProperty("Link");
            var name = runtimeEntityType.FindProperty("Name");
            var originalLink = runtimeEntityType.FindProperty("OriginalLink");
            var translationId = runtimeEntityType.FindProperty("TranslationId");
            var translator = runtimeEntityType.FindProperty("Translator");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTranslationTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, bool, string, string, string, string, string, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), (source.GetCurrentValue<string>(language) == null ? null : ((ValueComparer<string>)(((IProperty)language).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(language))), (source.GetCurrentValue<string>(link) == null ? null : ((ValueComparer<string>)(((IProperty)link).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(link))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(originalLink) == null ? null : ((ValueComparer<string>)(((IProperty)originalLink).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(originalLink))), (source.GetCurrentValue<string>(translationId) == null ? null : ((ValueComparer<string>)(((IProperty)translationId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(translationId))), (source.GetCurrentValue<string>(translator) == null ? null : ((ValueComparer<string>)(((IProperty)translator).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(translator))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(default(int))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<int>(default(int)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((QuranTranslationTable)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Translations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
