// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AudioFileName>k__BackingField")]
        public static extern ref string AudioFileName(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Aya>k__BackingField")]
        public static extern ref string Aya(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AyaId>k__BackingField")]
        public static extern ref int AyaId(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HizbId>k__BackingField")]
        public static extern ref int HizbId(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<JuzId>k__BackingField")]
        public static extern ref int JuzId(QuranTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SuraId>k__BackingField")]
        public static extern ref int SuraId(QuranTable @this);
    }
}
