// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using AlAnvar.Database.Tables;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AlAnvar.Database.CompiledModels
{
    public static class QuranTafsirNameTableUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(QuranTafsirNameTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Language>k__BackingField")]
        public static extern ref string Language(QuranTafsirNameTable @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(QuranTafsirNameTable @this);
    }
}
