// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace AlAnvar;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"AlAnvar.Views.HomeLandingPage", typeof(AlAnvar.Views.HomeLandingPage)},
        {"AlAnvar.Views.QuranPage", typeof(AlAnvar.Views.QuranPage)},
        {"AlAnvar.Views.QariPage", typeof(AlAnvar.Views.QariPage)},
        {"AlAnvar.Views.TranslationPage", typeof(AlAnvar.Views.TranslationPage)},
    };
}
