using System.Text;

namespace AlAnvar.Generators;

public static partial class StringBuilderExtensions
{
    internal static StringBuilder AppendFullHeader(this StringBuilder sb, string? fromData = null)
    {
        return sb.AppendAutoGeneratedHeader(fromData);
    }

    internal static StringBuilder AppendAutoGeneratedHeader(this StringBuilder sb, string? fromData = null)
    {
        return string.IsNullOrEmpty(fromData)
            ? sb.AppendLine("/// <auto-generated/>")
            : sb.AppendLine("/// <auto-generated>")
                .AppendLine($"/// From: {fromData}")
                .AppendLine("/// </auto-generated>");
    }
}

