// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment
using System;
using System.Collections.Generic;

namespace AlAnvar;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"AlAnvar.Views.HomeLandingPage", typeof(AlAnvar.Views.HomeLandingPage)},
        {"AlAnvar.Views.QuranPage", typeof(AlAnvar.Views.QuranPage)},
        {"AlAnvar.Views.TranslationsPage", typeof(AlAnvar.Views.TranslationsPage)},
        {"AlAnvar.Views.AudiosPage", typeof(AlAnvar.Views.AudiosPage)},
        {"AlAnvar.Views.TafsirPage", typeof(AlAnvar.Views.TafsirPage)},
        {"AlAnvar.Views.NotePage", typeof(AlAnvar.Views.NotePage)},
        {"AlAnvar.Views.SearchPage", typeof(AlAnvar.Views.SearchPage)},
    };
}
